export type AuthenticationMetricSeedRow = [string, string, string, string | null];

export const AUTHENTICATION_METRICS_SEED: readonly AuthenticationMetricSeedRow[] = [
  ["Bag", "General Condition", "Smell", "Genuine leather scent vs. chemical/artificial odors"],
  ["Bag", "General Condition", "Odor retention", "Perfume, smoke, storage smells"],
  ["Bag", "General Condition", "Structure", "Shape, firmness, and form"],
  ["Bag", "General Condition", "Size", "Compare with official brand specifications"],
  ["Bag", "General Condition", "Wear & Tear", "Overall scuffs, corner wear, condition grade"],
  ["Bag", "Exterior Leather / Canvas", "Scratches / scuffing", "Surface marks"],
  ["Bag", "Exterior Leather / Canvas", "Corner wear / rubbing", "Color/finish loss"],
  ["Bag", "Exterior Leather / Canvas", "Creasing / slouching", "Leather losing structure"],
  ["Bag", "Exterior Leather / Canvas", "Cracking", "Handles, glazing, folds"],
  ["Bag", "Exterior Leather / Canvas", "Fading / discoloration", "From sun or storage"],
  ["Bag", "Exterior Leather / Canvas", "Stains / marks", "Ink, water, transfer stains"],
  ["Bag", "Branding & Markings", "Font", "Thickness, spacing, accuracy"],
  ["Bag", "Branding & Markings", "Logo", "Design accuracy, placement"],
  ["Bag", "Branding & Markings", "Heat stamp", "Sharp, even, correct font/spacing"],
  ["Bag", "Branding & Markings", "Date codes / serial numbers", "Verify format (LV, Chanel, Dior, Hermès)"],
  ["Bag", "Branding & Markings", "Hallmarks / engravings", "Zippers, clasps, hardware"],
  ["Bag", "Branding & Markings", "Serial number/date code", "Correct placement, matches brand guidelines"],
  ["Bag", "Materials & Leather Quality", "Leather", "Texture, softness, consistency"],
  ["Bag", "Materials & Leather Quality", "Leather grain", "Hermès Togo, Clemence, Epsom; Chanel caviar; LV canvas"],
  ["Bag", "Materials & Leather Quality", "Canvas/fabric", "Durability, alignment of monograms"],
  ["Bag", "Materials & Leather Quality", "Exotics", "Crocodile/alligator stamps (Hermès: square/round near heat stamp) (it depends)"],
  ["Bag", "Functional Parts", "Color consistency", "Matches across parts"],
  ["Bag", "Functional Parts", "Weight", "Feels solid, heavy"],
  ["Bag", "Functional Parts", "Scratches", "Hairline surface marks"],
  ["Bag", "Functional Parts", "Tarnishing / dullness", "Fading finish"],
  ["Bag", "Functional Parts", "Plating loss", "Base metal exposed"],
  ["Bag", "Functional Parts", "Dents", "Deep marks"],
  ["Bag", "Functional Parts", "Zipper", "Smooth functionality, correct markings"],
  ["Bag", "Functional Parts", "Engraving", "Crisp, deep, correct font"],
  ["Bag", "Functional Parts", "Lock & keys", "Matching set, functional"],
  ["Bag", "Functional Parts", "Base feet", "Secure, not overly worn"],
  ["Bag", "Functional Parts", "Ring/strap attachments", "Firm, no loosening"],
  ["Bag", "Handles & Straps", "Darkening", "Especially Vachetta leather"],
  ["Bag", "Handles & Straps", "Edge wear", "Glazing peel/rubbing"],
  ["Bag", "Handles & Straps", "Stretching", "Straps elongating"],
  ["Bag", "Handles & Straps", "Cracks", "At stress points"],
  ["Bag", "Construction", "Stitching", "Even, tight, no overlaps (Hermès: saddle stitching)"],
  ["Bag", "Construction", "Loose stitches", "Threads lifting"],
  ["Bag", "Construction", "Fraying", "Edges unraveling"],
  ["Bag", "Construction", "Edge paint / glazing", "Smooth, no cracking/peeling"],
  ["Bag", "Construction", "Shape", "Holds form, no slouching"],
  ["Bag", "Lining & Interior", "Lining material", "Correct per brand (Chanel leather, LV microfiber)"],
  ["Bag", "Lining & Interior", "Stains / marks", "Ink, makeup, water spots"],
  ["Bag", "Lining & Interior", "Peeling / stickiness", "Common in vintage"],
  ["Bag", "Lining & Interior", "Stitching", "Secure, no loose threads"],
  ["Bag", "Lining & Interior", "Holes or tears", "Fabric integrity"],
  ["Bag", "Lining & Interior", "Stamp placement", "Chanel “Made in France/Italy,” etc."],
  ["Bag", "Packaging & Inclusions", "Dust bags", "Fabric quality, stitching, logo accuracy"],
  ["Bag", "Packaging & Inclusions", "Boxes", "Sturdy, correct finish, logo placement"],
  ["Bag", "Packaging & Inclusions", "Authenticity cards/booklets", "Font, hologram, layout, paper/card quality"],
  ["Bag", "Packaging & Inclusions", "Receipts / certificates", "Store details, tax info, printing quality"],
  ["Bag", "Packaging & Inclusions", "Care booklets/manuals", "Correct language, no spelling errors"],
  ["Bag", "Packaging & Inclusions", "Lock & Keys", "Check if the lock and keys are a matching pair and fully functional. Note any tarnishing."],
  ["Bag", "Packaging & Inclusions", "Other accessories", "Pouches,straps (brand-specific)"],
  ["Wallets/SLGs", "Brand Stamps & Logos", "Heat stamps / embossing", "Crisp, even, correct font & spacing"],
  ["Wallets/SLGs", "Brand Stamps & Logos", "Placement", "Matches brand standard (flap, seam, zipper area)"],
  ["Wallets/SLGs", "Brand Stamps & Logos", "Date codes / serial numbers", "Correct brand format (LV, Chanel, Hermès, etc.)"],
  ["Wallets/SLGs", "Brand Stamps & Logos", "Authenticity card / hologram sticker", "if applicable"],
  ["Wallets/SLGs", "Brand Stamps & Logos", "Wear & Tear", "Fading / rubbing off logos, Partial or illegible embossing "],
  ["Wallets/SLGs", "Leather & Materials", "Material", "Genuine luxury leather (calfskin, lambskin, Epsom, Togo, exotic skins)"],
  ["Wallets/SLGs", "Leather & Materials", "Texture", "Consistent grain, no bubbling or peeling"],
  ["Wallets/SLGs", "Leather & Materials", "Interior lining", "Leather, microfiber, or coated canvas (not plastic)"],
  ["Wallets/SLGs", "Leather & Materials", "Wear & Tear", "scratches/scuffs, corner wear, creasing /slouching, cracking (especially folds), fading/discoloration, stains (ink. Makeup, coins)"],
  ["Wallets/SLGs", "Stitching & Construction", "Stitching", "Straight, even, no loose threads (Hermès = saddle stitching)"],
  ["Wallets/SLGs", "Stitching & Construction", "Edges", "Clean glazing/paint, no overflow"],
  ["Wallets/SLGs", "Stitching & Construction", "Shape", "Balanced, structured, not lopsided"],
  ["Wallets/SLGs", "Stitching & Construction", "Wear & Tear", "loose threads/popped stitches, cracked or peeling edge glazing"],
  ["Wallets/SLGs", "Hardware", "Zippers", "Smooth function, correct branding (Éclair/Lampo/Riri vintage, branded LV modern)"],
  ["Wallets/SLGs", "Hardware", "Snaps / clasps", "Engraved logo, secure closure"],
  ["Wallets/SLGs", "Hardware", "Finish", "Polished, weighty, no flaking"],
  ["Wallets/SLGs", "Hardware", "Wear & Tear", "Scratches/tarnishing, Plating loss / fading, Worn engravings, Loose or broken snaps/zippers"],
  ["Wallets/SLGs", "Interior Features", "Card slots", "No holes, fraying, or stretching"],
  ["Wallets/SLGs", "Interior Features", "Bill compartment", "No tears, fraying, or lining issues"],
  ["Wallets/SLGs", "Interior Features", "Logo placement", "Matches brand standard"],
  ["Wallets/SLGs", "Interior Features", "Lining", "Durable, smooth, intact"],
  ["Wallets/SLGs", "Interior Features", "Wear & Tear", "Stretched slots, Peeling lining, Coin residue / dirt buildup, Torn dividers"],
  ["Wallets/SLGs", "Packaging & Inclusions", "Dust bag", "Quality fabric, correct logo, stitching, placement"],
  ["Wallets/SLGs", "Packaging & Inclusions", "Box", "Sturdy, correct finish & color, accurate logo"],
  ["Wallets/SLGs", "Packaging & Inclusions", "Authenticity cards / booklets", "Proper font, hologram, printing quality"],
  ["Wallets/SLGs", "Packaging & Inclusions", "Receipts / certificates", "Correct store details, tax info, layout"],
  ["Wallets/SLGs", "Packaging & Inclusions", "Care booklets / manuals", "Clear printing, no errors"],
  ["Wallets/SLGs", "Packaging & Inclusions", "Other accessories (if applicable)", "Extra straps, cloths, etc."],
  ["Shoes", "General Condition", "Smell", "Genuine leather scent vs. chemical/artificial odors"],
  ["Shoes", "General Condition", "Structure", "Shape, firmness, balance of pair"],
  ["Shoes", "General Condition", "Size", "Compare with brand specifications; both pairs must match"],
  ["Shoes", "General Condition", "Wear & Tear", "Overall scuffs, corner wear, condition grade"],
  ["Shoes", "Exterior Leather / Material", "Scratches / scuffing", "Surface marks"],
  ["Shoes", "Exterior Leather / Material", "Creasing", "Natural folds from wear"],
  ["Shoes", "Exterior Leather / Material", "Cracking", "Folds, uppers, or straps"],
  ["Shoes", "Exterior Leather / Material", "Fading / discoloration", "From sun or storage"],
  ["Shoes", "Exterior Leather / Material", "Stains / marks", "Ink, water, dirt transfer"],
  ["Shoes", "Materials & Leather Quality", "Leather", "Texture, softness, consistency"],
  ["Shoes", "Materials & Leather Quality", "Color", "Uniform shade, no patchy tones"],
  ["Shoes", "Materials & Leather Quality", "Wear & Tear", "Dryness, Peeling / flaking, Edge paint / glazing,"],
  ["Shoes", "Stitching", "Stitching", "Even, tight, clean, no overlaps"],
  ["Shoes", "Stitching", "Alignment", "Symmetrical on both shoes"],
  ["Shoes", "Stitching", "Wear & Tear", "Loose threads, Fraying / unraveling"],
  ["Shoes", "Branding & Markings", "Font", "Thickness, spacing, accuracy"],
  ["Shoes", "Branding & Markings", "Logo", "Placement, boldness, clarity"],
  ["Shoes", "Branding & Markings", "Serial number / date code", "Format & placement correct per brand"],
  ["Shoes", "Hardware & Buckles", "Hardware", "Consistent color, solid weight"],
  ["Shoes", "Hardware & Buckles", "Buckles", "Functional, engraved, aligned"],
  ["Shoes", "Hardware & Buckles", "Engravings", "Crisp, correct font & placement"],
  ["Shoes", "Hardware & Buckles", "Wear & Tear", "Hairline scratches, Tarnishing / dullness, Plating loss (base metal visible), Dents (Impact marks)"],
  ["Shoes", "Straps & Strap Holes", "Secure attachment", "No looseness"],
  ["Shoes", "Straps & Strap Holes", "No cracks, tears, or peeling", null],
  ["Shoes", "Straps & Strap Holes", "Even coloration", null],
  ["Shoes", "Straps & Strap Holes", "Wear & Tear", "Stretching (holes elongating), Edge wear (peeling or rubbing), Darkening (especially on light leather"],
  ["Shoes", "Soles", "Insole", null],
  ["Shoes", "Soles", "Smell check", "No strong odors"],
  ["Shoes", "Soles", "Intact lining", "No lifting or separation"],
  ["Shoes", "Soles", "Cleanliness", "No dirt buildup"],
  ["Shoes", "Soles", "No fading, tearing, or edge lifting", null],
  ["Shoes", "Soles", "Wear & Tear", "Imprints (footshape visible), Discoloration (sweat marks), Peeling / lifting (cushion or lining)"],
  ["Shoes", "Soles", "Outsole", null],
  ["Shoes", "Soles", "Clean and intact edges", null],
  ["Shoes", "Soles", "No sole separation/detachment", null],
  ["Shoes", "Wear Indicators", "Heel drag", "Worn down, uneven"],
  ["Shoes", "Wear Indicators", "Toe wear", "Scuffed or thinning"],
  ["Shoes", "Wear Indicators", "Sole thinning", "Smooth patches"],
  ["Shoes", "Wear Indicators", "Balding", "Lost tread/traction"],
  ["Shoes", "Wear Indicators", "Scuffing / abrasions", "Surface damage"],
  ["Shoes", "Wear Indicators", "Edge wear", "Fraying or thinning"],
  ["Shoes", "Wear Indicators", "Splitting / cracking", "Rubber/leather breaks"],
  ["Shoes", "Wear Indicators", "Midsole crumbling", "Foam breakdown"],
  ["Shoes", "Wear Indicators", "Uneven wear", "One side more worn"],
  ["Shoes", "Heels & Rubber Components", "Secure, stable, durable", null],
  ["Shoes", "Wear & Tear", "Heel chips", "Dents or cracks"],
  ["Shoes", "Wear & Tear", "Rubber wear", "Grip loss"],
  ["Shoes", "Wear & Tear", "Cracking", "Heel rubber/stacked leather"],
  ["Shoes", "Fit & Functionality", "Weight test", "Apply pressure for ~3 minutes"],
  ["Shoes", "Fit & Functionality", "Check for internal foam breakdown", null],
  ["Shoes", "Fit & Functionality", "Ensure both pairs feel stable & balanced", null],
  ["Shoes", "Packaging & Inclusions", "Dust bags", "Quality fabric, correct stitching/logo"],
  ["Shoes", "Packaging & Inclusions", "Boxes", "Sturdy, proper finish, logo correct"],
  ["Shoes", "Packaging & Inclusions", "Authenticity cards/booklets", "Font, hologram, printing quality"],
  ["Shoes", "Packaging & Inclusions", "Receipts/certificates", "Store details, tax info, correct layout"],
  ["Shoes", "Packaging & Inclusions", "Care booklets/manuals", "No errors, proper paper quality"],
  ["Shoes", "Packaging & Inclusions", "Other accessories", "Extra laces, heel tips, cleaning cloths, pouches, etc."],
  ["Belts", "General Condition", "Smell", "Genuine leather scent vs. chemical/artificial odors"],
  ["Belts", "General Condition", "Structure", "Shape, firmness, and overall form"],
  ["Belts", "General Condition", "Size", "Compare with official brand specifications"],
  ["Belts", "General Condition", "Wear & Tear", "Evaluate scuffs, corner wear, assign condition grade"],
  ["Belts", "Materials & Leather Quality", "Leather", "Texture, softness, color consistency"],
  ["Belts", "Wear & Tear (Strap)", "Creasing", "Natural fold lines near holes"],
  ["Belts", "Wear & Tear (Strap)", "Wrinkling", "Fine surface lines from use"],
  ["Belts", "Wear & Tear (Strap)", "Scuffing / scratches", "Surface marks from friction"],
  ["Belts", "Wear & Tear (Strap)", "Edge wear / rubbing", "Fading, fraying, or finish loss"],
  ["Belts", "Wear & Tear (Strap)", "Stretching", "Elongation around belt holes"],
  ["Belts", "Wear & Tear (Strap)", "Cracking / peeling", "Surface finish breakdown"],
  ["Belts", "Wear & Tear (Strap)", "Discoloration / fading", "Uneven tones, especially light leathers"],
  ["Belts", "Wear & Tear (Strap)", "Staining / water spots", "Visible marks from liquids/oils"],
  ["Belts", "Stitching & Edge Paint", "Stitching", "Even, tight, clean, no loose threads"],
  ["Belts", "Stitching & Edge Paint", "Wear & Tear", "Fraying (threads coming loose), Broken stitches (gaps in seams)"],
  ["Belts", "Edge Paint / Glazing", "Smooth, even finish", null],
  ["Belts", "Wear & Tear", "Cracks", "Splitting or lifting"],
  ["Belts", "Wear & Tear", "Peeling", "Edge finish coming off"],
  ["Belts", "Branding & Markings", "Font", "Correct thickness, spacing, alignment"],
  ["Belts", "Branding & Markings", "Logo", "Boldness, accuracy, correct placement"],
  ["Belts", "Branding & Markings", "Serial number / date code", "Authentic format & correct placement"],
  ["Belts", "Hardware & Buckle", "Hardware", "Solid weight, consistent color, correct quality"],
  ["Belts", "Hardware & Buckle", "Engraving", "Clear, deep, correct font style"],
  ["Belts", "Wear & Tear", "Hairline scratches", "Light marks"],
  ["Belts", "Wear & Tear", "Surface scratches / scuffing", "More visible wear"],
  ["Belts", "Wear & Tear", "Tarnishing / discoloration", "Plating dullness"],
  ["Belts", "Wear & Tear", "Chipping / plating loss", "Base metal showing"],
  ["Belts", "Wear & Tear", "Dents", "Deeper impact marks"],
  ["Belts", "Wear & Tear", "Loose mechanism", "Buckle/prong not holding securely"],
  ["Belts", "Packaging & Inclusions", "Authenticity:", null],
  ["Belts", "Packaging & Inclusions", "Dust bags", "Quality material, stitching, logo placement"],
  ["Belts", "Packaging & Inclusions", "Boxes", "Sturdy, proper texture, accurate logo"],
  ["Belts", "Packaging & Inclusions", "Authenticity cards / booklets", "Correct font, layout, printing, hologram (if any)"],
  ["Belts", "Packaging & Inclusions", "Receipts / certificates", "Store details, tax info, correct printing"],
  ["Belts", "Packaging & Inclusions", "Care booklets / manuals", "Proper printing, no spelling errors"],
  ["Belts", "Packaging & Inclusions", "Other accessories", "Pouches, cleaning cloths, straps (if brand-specific)"],
  ["Shades", "General Condition", "Font", "Correct thickness, spacing, accuracy"],
  ["Shades", "General Condition", "Logo", "Placement, boldness, accuracy"],
  ["Shades", "General Condition", "Structure", "Shape, firmness, overall alignment"],
  ["Shades", "General Condition", "Size", "Compare dimensions with brand specifications"],
  ["Shades", "General Condition", "Condition grade", "Assign based on scuffs, corner wear, and use"],
  ["Shades", "Wear & Tear", "Warping", "Frame shape distorted"],
  ["Shades", "Wear & Tear", "Bending", "Arms or bridge misaligned"],
  ["Shades", "Wear & Tear", "Loose fit", "Arms not holding firmly"],
  ["Shades", "Wear & Tear", "Stretching", "Arms widened, reduced grip"],
  ["Shades", "Frame", "Inspect for scratches, warping, discoloration", null],
  ["Shades", "Wear & Tear", "Scratches", "Surface marks"],
  ["Shades", "Wear & Tear", "Discoloration", "Faded or uneven tone"],
  ["Shades", "Wear & Tear", "Warping", "Frame not sitting flat/aligned"],
  ["Shades", "Arms of Frame", "Check symmetry, tightness, size, attachment", null],
  ["Shades", "Arms of Frame", "Ensure arms hold firmly without looseness or overstretching", null],
  ["Shades", "Wear & Tear", "Bending", "Arms not symmetrical"],
  ["Shades", "Wear & Tear", "Looseness", "Arms swing freely, weak grip"],
  ["Shades", "Wear & Tear", "Tightness", "Hinges overly stiff"],
  ["Shades", "Wear & Tear", "Stretching", "Arms widened, grip reduced"],
  ["Shades", "Nose Pads", "Check presence, alignment, overall condition", null],
  ["Shades", "Wear & Tear", "Missing pads", "One or both absent"],
  ["Shades", "Wear & Tear", "Bends", "Pads crooked/misaligned"],
  ["Shades", "Wear & Tear", "Degraded material", "Yellowing, cracking, sticky texture"],
  ["Shades", "Wear & Tear", "Detached", "Pads loose or falling off"],
  ["Shades", "Screws", "Verify screws present, secure, matching", null],
  ["Shades", "Wear & Tear", "Missing screws", "One or more absent"],
  ["Shades", "Wear & Tear", "Loose screws", "Hinges unstable"],
  ["Shades", "Wear & Tear", "Rust / discoloration", "From age/exposure"],
  ["Shades", "Lenses", "Inspect clarity, tint, and quality", null],
  ["Shades", "Wear & Tear", "Micro scratches", "Visible only in light"],
  ["Shades", "Wear & Tear", "Surface scratches", "Noticeable, minor effect"],
  ["Shades", "Wear & Tear", "Deep scratches", "Affect vision"],
  ["Shades", "Wear & Tear", "Scuffing / abrasions", "Cloudy or hazy spots"],
  ["Shades", "Wear & Tear", "Delamination / peeling", "Coating lifting/flaking"],
  ["Shades", "Wear & Tear", "Discoloration / fading", "Uneven or lost tint vibrancy"],
  ["Shades", "Wear & Tear", "Clouding / haze", "Age or chemical exposure"],
  ["Shades", "Packaging & Inclusions", "Authenticity:", null],
  ["Shades", "Packaging & Inclusions", "Dust bags", "High-quality fabric, correct logo, stitching"],
  ["Shades", "Packaging & Inclusions", "Boxes", "Sturdy, correct texture/color/logo"],
  ["Shades", "Packaging & Inclusions", "Authenticity cards/booklets", "Correct font, layout, hologram (if applicable)"],
  ["Shades", "Packaging & Inclusions", "Receipts / certificates", "Store details, tax info, accurate format"],
  ["Shades", "Packaging & Inclusions", "Care booklets / manuals", "Proper quality, no errors"],
  ["Shades", "Packaging & Inclusions", "Other accessories", "Branded extras (pouches, cloths, etc.)"],
  ["Watch", "General Condition", "Font", "Check thickness, spacing, and accuracy of text."],
  ["Watch", "General Condition", "Logo", "Verify boldness, design accuracy, and correct placement."],
  ["Watch", "General Condition", "Serial Number & Date Code", "Confirm authenticity, format, and placement per brand guidelines."],
  ["Watch", "General Condition", "Structure", "Assess shape, firmness, and overall form."],
  ["Watch", "General Condition", "Size", "Measure dimensions and compare with official brand specifications."],
  ["Watch", "General Condition", "Wear & Tear Assessment", "Evaluate scuffs, scratches, and overall condition. Assign a grade."],
  ["Watch", "Case & Bezel (Metal Body of the Watch)", "Inspect case for cracks, dents, and secure attachment.", null],
  ["Watch", "Wear & Tear", "Hairline scratches", null],
  ["Watch", "Wear & Tear", "Surface scratches / scuffing", null],
  ["Watch", "Wear & Tear", "Dents / dings", null],
  ["Watch", "Wear & Tear", "Polishing marks", "signs of refinishing"],
  ["Watch", "Wear & Tear", "Tarnishing / discoloration", null],
  ["Watch", "Wear & Tear", "Bezel wear", "scratches, fading, or worn engravings"],
  ["Watch", "Crystal (Glass)", "Check clarity, transparency, and condition.", null],
  ["Watch", "Wear & Tear", "Micro scratches", null],
  ["Watch", "Wear & Tear", "Surface scratches", null],
  ["Watch", "Wear & Tear", "Chips / nicks", "edges"],
  ["Watch", "Wear & Tear", "Cracks", null],
  ["Watch", "Wear & Tear", "Hazing / cloudiness", null],
  ["Watch", "Strap / Bracelet", "Inspect for cracks, discoloration, loose stitching, dents, or weak attachment.", null],
  ["Watch", "Wear & Tear", "Stretching", "loose bracelet links"],
  ["Watch", "Wear & Tear", "Surface scratches", "links, clasp"],
  ["Watch", "Wear & Tear", "Polish loss", "finish fading"],
  ["Watch", "Wear & Tear", "Discoloration / fading", "leather or rubber"],
  ["Watch", "Wear & Tear", "Creasing / wrinkling", "leather"],
  ["Watch", "Wear & Tear", "Cracking / peeling", "aged leather/rubber"],
  ["Watch", "Wear & Tear", "Fraying", "fabric or stitching"],
  ["Watch", "Clasp / Buckle", "Check hardware consistency", "weight, color, material"],
  ["Watch", "Clasp / Buckle", "Verify engraving", "depth, clarity, font style"],
  ["Watch", "Wear & Tear", "Scratches", null],
  ["Watch", "Wear & Tear", "Tarnishing / fading", null],
  ["Watch", "Wear & Tear", "Loose clasp", "doesn’t secure properly"],
  ["Watch", "Dial & Hands", "Confirm proper hand rotation and alignment.", null],
  ["Watch", "Wear & Tear", "Patina", "natural aging"],
  ["Watch", "Wear & Tear", "Discoloration", "spots, fading"],
  ["Watch", "Wear & Tear", "Lume degradation", "glow paint fading/cracking"],
  ["Watch", "Crown", "Test pull/push", "hands and date aperture must function properly."],
  ["Watch", "Wear & Tear", "Loose crown", "wobbly, unstable"],
  ["Watch", "Wear & Tear", "Thread wear", "difficulty screwing/pulling"],
  ["Watch", "Movement (Inside)", "Listen for unusual noises.", null],
  ["Watch", "Movement (Inside)", "Test accuracy & power reserve.", null],
  ["Watch", "Wear & Tear", "Running but untested", "working, accuracy unknown"],
  ["Watch", "Wear & Tear", "Requires service", "time inaccuracy"],
  ["Watch", "Wear & Tear", "Power reserve issues", "not holding charge"],
  ["Watch", "Packaging & Inclusions", "Authenticity:", null],
  ["Watch", "Packaging & Inclusions", "Boxes", "Sturdy, correct texture/color/logo"],
  ["Watch", "Packaging & Inclusions", "Authenticity cards/booklets", "Correct font, layout, hologram (if applicable)"],
  ["Watch", "Packaging & Inclusions", "Receipts / certificates", "Store details, tax info, accurate format"],
  ["Watch", "Packaging & Inclusions", "Care booklets / manuals", "Proper quality, no errors"],
  ["Watch", "Packaging & Inclusions", "Other accessories", "Branded extras (pouches, cloths, etc.)"],
  ["Scarves/Twillies", "General Condition", "Labels", "Verify Hermès silk tags, woven care labels, and correct fonts."],
  ["Scarves/Twillies", "General Condition", "Hems", "Confirm hand-rolled hems (Hermès: rolled toward the front design)."],
  ["Scarves/Twillies", "General Condition", "Print alignment", "Sharp, symmetrical motifs with no misprints."],
  ["Scarves/Twillies", "General Condition", "Material feel", "Authentic silk is smooth with a crisp “hand”; cashmere is ultra-fine and soft."],
  ["Scarves/Twillies", "General Condition", "Stamps / Signatures", "Look for an artist's signature hidden in design."],
  ["Scarves/Twillies", "General Condition", "Packaging", "Hermès orange box, Chanel tissue paper, Dior ribbon, etc. (packaging supports but does not prove authenticity)."],
  ["Scarves/Twillies", "General Condition", "Font", "Check thickness, spacing, and accuracy."],
  ["Scarves/Twillies", "General Condition", "Logo", "Verify boldness, design accuracy, and placement."],
  ["Scarves/Twillies", "General Condition", "Size", "Measure dimensions against brand specifications."],
  ["Scarves/Twillies", "General Condition", "Wear & Tear Assessment", "Evaluate overall condition (fabric, edges, print, inclusions) and assign grade."],
  ["Scarves/Twillies", "Fabric", "Inspect weave, density, and texture.", null],
  ["Scarves/Twillies", "Wear & Tear", "Snags / pulls", "Loose threads."],
  ["Scarves/Twillies", "Wear & Tear", "Runs", "Lines from pulled threads."],
  ["Scarves/Twillies", "Wear & Tear", "Fraying", "Edges or hems unraveling."],
  ["Scarves/Twillies", "Wear & Tear", "Pilling / fuzzing", "Fabric balls (wool/cashmere)."],
  ["Scarves/Twillies", "Wear & Tear", "Thinning / worn areas", "Reduced density."],
  ["Scarves/Twillies", "Wear & Tear", "Stains / spots", "Makeup, water, perfume, oil."],
  ["Scarves/Twillies", "Wear & Tear", "Discoloration / fading", "From sun or washing."],
  ["Scarves/Twillies", "Wear & Tear", "Yellowing", "Age-related."],
  ["Scarves/Twillies", "Wear & Tear", "Odor retention", "Perfume, musty, or storage smell."],
  ["Scarves/Twillies", "Edges & Hemming", "Verify quality of hems and stitching.", null],
  ["Scarves/Twillies", "Wear & Tear", "Rolled hems softened / flattened.", null],
  ["Scarves/Twillies", "Wear & Tear", "Loose stitching", "Threads coming undone."],
  ["Scarves/Twillies", "Wear & Tear", "Fraying edges", "Raw threads visible."],
  ["Scarves/Twillies", "Print & Design", "Check vibrancy, registration, and sharpness.", null],
  ["Scarves/Twillies", "Wear & Tear", "Color fading", "Uneven dullness."],
  ["Scarves/Twillies", "Wear & Tear", "Print cracking", "Weakening or peeling (treated fabrics)."],
  ["Scarves/Twillies", "Packaging & Inclusions", "Authenticity:", null],
  ["Scarves/Twillies", "Packaging & Inclusions", "Boxes", "Sturdy, correct texture/color/logo"],
  ["Scarves/Twillies", "Packaging & Inclusions", "Authenticity cards/booklets", "Correct font, layout, hologram (if applicable)"],
  ["Scarves/Twillies", "Packaging & Inclusions", "Receipts / certificates", "Store details, tax info, accurate format"],
  ["Scarves/Twillies", "Packaging & Inclusions", "Care booklets / manuals", "Proper quality, no errors"],
  ["Scarves/Twillies", "Packaging & Inclusions", "Other accessories", "Branded extras (pouches, cloths, etc.)"],
  ["Hats/Caps", "General Condition", "Labels & Tags", "Inspect brand tags for font, placement, stitching, and material (e.g., Hermès silk tags, Chanel metal logo plaques)."],
  ["Hats/Caps", "General Condition", "Stitching", "Even, neat, and consistent; no loose threads."],
  ["Hats/Caps", "General Condition", "Logo / Branding", "Embroidery, embossing, or hardware should be crisp, aligned, and properly finished."],
  ["Hats/Caps", "General Condition", "Lining", "Confirm brand-specific linings (e.g., Chanel CC motif, Hermès silk lining)."],
  ["Hats/Caps", "General Condition", "Hardware", "If present, engraved logos must use correct font, placement, and finish."],
  ["Hats/Caps", "General Condition", "Material Quality", "Luxury hats use high-grade felt, straw, cotton, wool, or blends."],
  ["Hats/Caps", "General Condition", "Texture", "Weight, and finish should match brand standards."],
  ["Hats/Caps", "Fabric", "Inspect material, weave, and overall quality.", null],
  ["Hats/Caps", "Wear & Tear", "Snags / pulls", "Threads caught or lifted."],
  ["Hats/Caps", "Wear & Tear", "Runs", "Visible lines from pulled threads (common in silk)."],
  ["Hats/Caps", "Wear & Tear", "Fraying", "Edges or seams unraveling."],
  ["Hats/Caps", "Wear & Tear", "Pilling / fuzzing", "Small fabric balls forming (wool/cashmere)."],
  ["Hats/Caps", "Wear & Tear", "Thinning / worn areas", "Fabric losing density from friction."],
  ["Hats/Caps", "Wear & Tear", "Stains / spots", "Water, makeup, perfume, oil marks."],
  ["Hats/Caps", "Wear & Tear", "Deformation / misshaping", "Brim or crown losing structure."],
  ["Hats/Caps", "Wear & Tear", "Fading / discoloration", "From sun, sweat, or cleaning."],
  ["Hats/Caps", "Wear & Tear", "Sweatband staining", "Makeup or perspiration marks inside hat."],
  ["Hats/Caps", "Wear & Tear", "Yellowing", "Age-related discoloration (common in lighter colors)."],
  ["Hats/Caps", "Wear & Tear", "Odor retention", "Musty, perfume, or storage smell."],
  ["Hats/Caps", "Packaging & Inclusions", "Authenticity:", null],
  ["Hats/Caps", "Packaging & Inclusions", "Dust bag", "Quality fabric, correct logo, stitching, placement"],
  ["Hats/Caps", "Packaging & Inclusions", "Box", "Sturdy, correct finish & color, accurate logo"],
  ["Hats/Caps", "Packaging & Inclusions", "Authenticity cards / booklets", "Proper font, hologram, printing quality"],
  ["Hats/Caps", "Packaging & Inclusions", "Receipts / certificates", "Correct store details, tax info, layout"],
  ["Hats/Caps", "Packaging & Inclusions", "Care booklets / manuals", "Clear printing, no errors"],
  ["Hats/Caps", "Packaging & Inclusions", "Other accessories (if applicable)", "Extra straps, cloths, etc."],
  ["High End Jewelry", "Hallmarks & Stamps", "Brand Signature", "Verify precise font, placement, and depth (e.g., Cartier, “750” for 18k, VCA hallmark)."],
  ["High End Jewelry", "Hallmarks & Stamps", "Metal Purity Marks", "Look for 18k/750, Pt950 (platinum), Au750, etc."],
  ["High End Jewelry", "Hallmarks & Stamps", "Country & Maker’s Marks", "VCA includes French assay marks; Cartier uses unique stamps depending on collection."],
  ["High End Jewelry", "Hallmarks & Stamps", "Serial Numbers", "Each authentic Cartier or VCA piece has a unique, cleanly laser-engraved number."],
  ["High End Jewelry", "Wear & Tear", "Faded hallmarks", "May soften from repeated polishing."],
  ["High End Jewelry", "Wear & Tear", "Engravings", "Can lose clarity if resized, polished, or repaired."],
  ["High End Jewelry", "Craftsmanship & Construction", "Size", "Measure dimensions against brand specifications"],
  ["High End Jewelry", "Craftsmanship & Construction", "Weight", "Authentic pieces feel substantial; never hollow or unusually light."],
  ["High End Jewelry", "Craftsmanship & Construction", "Finishing", "Smooth edges, even polish, no rough soldering."],
  ["High End Jewelry", "Craftsmanship & Construction", "Symmetry", "Motifs (e.g., VCA clovers) should be perfectly balanced."],
  ["High End Jewelry", "Craftsmanship & Construction", "Clasps & Fastenings", "Secure, with brand engravings where applicable."],
  ["High End Jewelry", "Craftsmanship & Construction", "Stone Settings", "Prongs uniform, stones set tightly (never glued)."],
  ["High End Jewelry", "Wear & Tear", "Clasps loosened / hinges weakened / springs losing tension.", null],
  ["High End Jewelry", "Wear & Tear", "Prongs bent, worn down, or risking stone security.", null],
  ["High End Jewelry", "Wear & Tear", "Edges dulled from polishing or long-term wear.", null],
  ["High End Jewelry", "Materials", "Metals", "Only solid gold or platinum; never plated."],
  ["High End Jewelry", "Materials", "Gemstones", "High clarity, uniform color, consistent with brand’s strict quality control."],
  ["High End Jewelry", "Materials", "Enamel / Inlays (MOP, onyx, etc.)", "Cleanly cut, evenly applied, flush with setting."],
  ["High End Jewelry", "Wear & Tear", "Metals", "Hairline scratches, scuffing, dents, tarnishing, platinum patina, rhodium wear on white gold."],
  ["High End Jewelry", "Wear & Tear", "Gemstones", "Chips, scratches (especially softer stones like opal, turquoise, pearls), discoloration, or loosened settings."],
  ["High End Jewelry", "Wear & Tear", "Enamel / Inlays", "Chipping, surface scratches, fading/discoloration from sunlight or chemicals."],
  ["High End Jewelry", "Packaging & Inclusions", "Authenticity:", null],
  ["High End Jewelry", "Packaging & Inclusions", "Dust bag", "Quality fabric, correct logo, stitching, placement"],
  ["High End Jewelry", "Packaging & Inclusions", "Box", "Sturdy, correct finish & color, accurate logo"],
  ["High End Jewelry", "Packaging & Inclusions", "Authenticity cards / booklets", "Proper font, hologram, printing quality"],
  ["High End Jewelry", "Packaging & Inclusions", "Receipts / certificates", "Correct store details, tax info, layout"],
  ["High End Jewelry", "Packaging & Inclusions", "Care booklets / manuals", "Clear printing, no errors"],
  ["High End Jewelry", "Packaging & Inclusions", "Other accessories (if applicable)", "Extra straps, cloths, etc."],
  ["Designer Costumes Accessories", "Brand Markings & Stamps", "Signatures / Logos", "Crisp, clean, correct fonts (e.g., CHANEL ® plaque, Dior engraving, Gucci GG)."],
  ["Designer Costumes Accessories", "Brand Markings & Stamps", "Placement", "Located in brand-consistent areas (e.g., back of brooch, underside of belt buckle, inside hair clips)."],
  ["Designer Costumes Accessories", "Brand Markings & Stamps", "Date Codes / Season Marks", "Chanel often includes seasonal stamps (e.g., “23A” for Fall 2023)."],
  ["Designer Costumes Accessories", "Brand Markings & Stamps", "Made In Markings", "Should specify correct origin (e.g., Made in Italy, Made in France)."],
  ["Designer Costumes Accessories", "Wear & Tear", "Fading stamps", "Logos/date codes rubbing off from friction/polishing."],
  ["Designer Costumes Accessories", "Wear & Tear", "Scratched plaques", "Surface scratches on metal plates."],
  ["Designer Costumes Accessories", "Wear & Tear", "Loose markings", "Detached or unstable plaques/tags."],
  ["Designer Costumes Accessories", "Materials & Construction", "Size", "Measure dimensions against brand specifications"],
  ["Designer Costumes Accessories", "Materials & Construction", "Weight & Feel", "Feels solid/substantial; not overly light or hollow."],
  ["Designer Costumes Accessories", "Materials & Construction", "Plating / Enamel Quality", "Smooth, even, no bubbling, peeling, or rough edges."],
  ["Designer Costumes Accessories", "Materials & Construction", "Resin / Acrylic", "High-quality, uniform color, polished (e.g., Chanel, Dior)."],
  ["Designer Costumes Accessories", "Materials & Construction", "Crystals / Rhinestones", "Evenly set, aligned, no glue residue."],
  ["Designer Costumes Accessories", "Materials & Construction", "Hardware", "Clasps, screws, hinges firmly secured and functional."],
  ["Designer Costumes Accessories", "Wear & Tear", "Hairline scratches on metals.", null],
  ["Designer Costumes Accessories", "Wear & Tear", "Plating loss / fading", "base metal showing"],
  ["Designer Costumes Accessories", "Wear & Tear", "Resin/acrylic chipping or cracked edges.", null],
  ["Designer Costumes Accessories", "Wear & Tear", "Resin/acrylic discoloration", "yellowing/fading"],
  ["Designer Costumes Accessories", "Wear & Tear", "Loose / missing stones.", null],
  ["Designer Costumes Accessories", "Craftsmanship", "Stitching (if leather trim is present)", "Neat, consistent, symmetrical."],
  ["Designer Costumes Accessories", "Craftsmanship", "Symmetry", "Logos, motifs, shapes balanced and proportionate."],
  ["Designer Costumes Accessories", "Craftsmanship", "Fastenings", "Clasps, pin backs, barrette clips secure and smooth in function."],
  ["Designer Costumes Accessories", "Wear & Tear", "Fraying stitching", "Loose or uneven thread."],
  ["Designer Costumes Accessories", "Wear & Tear", "Weakened clasps", "Not closing securely, losing tension."],
  ["Designer Costumes Accessories", "Wear & Tear", "Loose hinges", "Brooches/clips/bangles not holding firmly."],
  ["Designer Costumes Accessories", "Wear & Tear", "Bent metal", "Thin trims or fastenings warped out of shape."],
  ["Designer Costumes Accessories", "Packaging & Inclusions", "Authenticity:", null],
  ["Designer Costumes Accessories", "Packaging & Inclusions", "Dust bag", "Quality fabric, correct logo, stitching, placement"],
  ["Designer Costumes Accessories", "Packaging & Inclusions", "Box", "Sturdy, correct finish & color, accurate logo"],
  ["Designer Costumes Accessories", "Packaging & Inclusions", "Authenticity cards / booklets", "Proper font, hologram, printing quality"],
  ["Designer Costumes Accessories", "Packaging & Inclusions", "Receipts / certificates", "Correct store details, tax info, layout"],
  ["Designer Costumes Accessories", "Packaging & Inclusions", "Care booklets / manuals", "Clear printing, no errors"],
  ["Designer Costumes Accessories", "Packaging & Inclusions", "Other accessories (if applicable)", "Extra straps, cloths, etc."],
  ["Designer Clothes", "Brand Labels & Tags", "Main label", "stitching neat, centered, correct font & placement."],
  ["Designer Clothes", "Brand Labels & Tags", "Care label", "fabric composition, care instructions, country of origin; consistent font/spacing."],
  ["Designer Clothes", "Brand Labels & Tags", "Size tag", "proportional, aligned, correct format (FR/IT/US)."],
  ["Designer Clothes", "Brand Labels & Tags", "Season/style codes", "collection codes, style numbers, internal tags (e.g., Chanel, Dior)."],
  ["Designer Clothes", "Brand Labels & Tags", "Made in markings", "clear and brand-consistent (“Made in Italy/France”)."],
  ["Designer Clothes", "Wear & Tear", "Faded, curled, detached, or illegible labels.", null],
  ["Designer Clothes", "Fabric & Materials", "Luxury textiles", "wool, silk, cashmere, cotton, or blends; smooth, high-quality."],
  ["Designer Clothes", "Fabric & Materials", "Lining", "silk/viscose, properly aligned, no bubbling."],
  ["Designer Clothes", "Fabric & Materials", "Weight & drape", "hangs naturally, not stiff or flimsy."],
  ["Designer Clothes", "Wear & Tear", "Pilling", "wool/cashmere"],
  ["Designer Clothes", "Wear & Tear", "Snags/pulls.", null],
  ["Designer Clothes", "Wear & Tear", "Fading/discoloration", "sun, sweat"],
  ["Designer Clothes", "Wear & Tear", "Stains/marks", "makeup, deodorant, perfume, food"],
  ["Designer Clothes", "Wear & Tear", "Odor retention", "smoke, perfume, storage"],
  ["Designer Clothes", "Wear & Tear", "Thinning/worn spots.", null],
  ["Designer Clothes", "Stitching & Construction", "Seams", "straight, secure, even."],
  ["Designer Clothes", "Stitching & Construction", "Finishing", "clean hems, overlocked or hand-finished edges."],
  ["Designer Clothes", "Stitching & Construction", "Symmetry", "prints/patterns aligned across seams."],
  ["Designer Clothes", "Wear & Tear", "Loose threads.", null],
  ["Designer Clothes", "Wear & Tear", "Open seams.", null],
  ["Designer Clothes", "Wear & Tear", "Fraying hems.", null],
  ["Designer Clothes", "Hardware & Embellishments", "Zippers/buttons", "branded, engraved (e.g., Lampo, YKK, Chanel CC)."],
  ["Designer Clothes", "Hardware & Embellishments", "Embellishments", "sequins, crystals, embroidery secure and neatly attached."],
  ["Designer Clothes", "Hardware & Embellishments", "Fastenings", "hooks, snaps, clasps sturdy and functional."],
  ["Designer Clothes", "Wear & Tear", "Scratches/tarnishing on metal parts.", null],
  ["Designer Clothes", "Wear & Tear", "Missing buttons or embellishments.", null],
  ["Designer Clothes", "Wear & Tear", "Loose appliqués or embroidery.", null],
  ["Designer Clothes", "Fit & Structure", "Tailoring", "precise, structured."],
  ["Designer Clothes", "Fit & Structure", "Shoulders & seams", "sit flush, proportional."],
  ["Designer Clothes", "Fit & Structure", "Draping", "maintains silhouette, no sagging."],
  ["Designer Clothes", "Wear & Tear", "Stretching/misshaping", "e.g., knitwear losing elasticity, shoulder droop"],
  ["Designer Clothes", "Wear & Tear", "Shrinkage", "heat or improper washing"],
  ["Designer Clothes", "Packaging & Inclusions", "Authenticity:", null],
  ["Designer Clothes", "Packaging & Inclusions", "Dust bag", "Quality fabric, correct logo, stitching, placement"],
  ["Designer Clothes", "Packaging & Inclusions", "Box", "Sturdy, correct finish & color, accurate logo"],
  ["Designer Clothes", "Packaging & Inclusions", "Authenticity cards / booklets", "Proper font, hologram, printing quality"],
  ["Designer Clothes", "Packaging & Inclusions", "Receipts / certificates", "Correct store details, tax info, layout"],
  ["Designer Clothes", "Packaging & Inclusions", "Care booklets / manuals", "Clear printing, no errors"],
  ["Designer Clothes", "Packaging & Inclusions", "Other accessories (if applicable)", "Extra straps, cloths, etc."],
];
